package com.myServlets.example;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

// This class extends HttpServlet, which makes it a "Web Component"
public class HelloServlet extends HttpServlet {

    // doGet is called when someone visits the URL in a browser
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        // 1. Tell the browser we are sending HTML
        resp.setContentType("text/html");

        // 2. Get the "pen" to write the response
        PrintWriter out = resp.getWriter();

        // 3. Write the HTML
        out.println("<html><body>");
        out.println("<h1>Hello World!</h1>");
        out.println("<p>This response was generated by Java code in HelloServlet.</p>");
        out.println("</body></html>");
    }
}